### ISSUE TITLE
Add Tremor-Server benchmark for Rust

### ISSUE THREAD

**Issue by mjp41** [SchrodingerZhu/bench_suite#7]
Tremor-server could be a good benchmark to add to your list.  Here are some instructions on how to run it:
   https://github.com/microsoft/snmalloc/issues/154#issuecomment-602271865

@licenser, @darach

**Comment by darach** [comment]
Let us know how we can help/assist here.

**Comment by Licenser** [comment]
What Darach said!

**Comment by SchrodingerZhu** [comment]
Great! will look into it by this weekend :)

**Comment by SchrodingerZhu** [comment]
@Licenser 
I plan is to add these crates as deps and write the server code in my `rust_bencher`. 
```
tremor-runtime = { path = "../tremor-runtime", default-features = false}
tremor-api = { path = "../tremor-runtime/tremor-api", default-features = false}
tremor-pipeline = { path = "../tremor-runtime/tremor-pipeline", default-features = false}
```
A small problem here: 
```
  --> /home/schrodinger/PycharmProjects/allocator-bench/tremor-runtime/src/offramp/rest.rs:79:38
   |
79 |                     c = c.set_header(&h, v.as_str());
   |                                      ^^ expected `str`, found struct `http::header::name::HeaderName`
   |
   = note: expected reference `&'static str`
              found reference `&http::header::name::HeaderName`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `tremor-runtime`.

To learn more, run the command again with --verbose.
```

This seems to be problem caused by `http`. I should use version < 2, but it is somehow polluted. I see there is a pull request about `http` at tremor runtime repo, should I just wait for that?

I should be able to get the code compiled, but it is a little bit wired that my other crates do not rely on `http`.
```toml
exec_time = "*"
simd-json = "*"
rayon = "*"
rand = "*"
xactor = "*"
async-std = "*"
async-trait= "*"
crossbeam = "*"
crossbeam-skiplist = { git = "https://github.com/crossbeam-rs/crossbeam", features = ["nightly"] }
hashbrown = "*"
mimalloc = { version = "*", default-features = false }
jemallocator = "*"
wee_alloc = "*"
tcmalloc = "*"
snmalloc-rs = "*"
rpmalloc = "*"
structopt = "*"
dlmalloc = { version = "*", features = ["global"]}
tremor-runtime = { path = "../tremor-runtime", default-features = false}
tremor-api = { path = "../tremor-runtime/tremor-api", default-features = false}
tremor-pipeline = { path = "../tremor-runtime/tremor-pipeline", default-features = false}
```
